Farmveda/Farmveda/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('web/', include('web.urls')),
    path('', include('django.contrib.auth.urls'))

]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Farmveda/web/urls.py
from django.urls import path
from django.conf.urls import include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'web'

urlpatterns = [
    path('buyersignup/', views.buyer_signup_view, name='buyer_signup'), 
    path('sellersignup/', views.seller_signup_view, name='seller_signup'),
    path('login/', views.login_view , name='login'), 
    path('loggedin/', views.login_index , name='login_index'),
    path('logout/', views.logout_view, name='logout'),
    path('home/', views.home, name="home"),
    path('options/', views.signup_options,name="signup_options"),
    path('myprofile/',views.my_profile,name="my_profile"),
    path('myprofile/edit/',views.edit_profile,name="edit_profile"),
    path('myprofile/password/',views.change_password,name="change_password"),
    path('search/',include('haystack.urls')),
    path('create/',views.product_create_view,name='product_create_view'),
    path('product/(?P<pk>\d+)/',views.product,name="product"),
    path('product/edit/(?P<pk>\d+)/',views.edit_details,name="edit_details"),
    path('product/delete/(?P<pk>\d+)/',views.delete_product,name="delete_product"),
    path('wishlist/',views.view_wishlist,name="wishlist"),
    path('add-wishlist/(?P<pk>\d+)/',views.add_to_wishlist,name="add-wishlist"),
    path('remove-wishlist/(?P<pk>\d+)/',views.remove_wishlist,name="remove-wishlist"),
    path('search_product/(?P<pk>\d+)/',views.search_product, name="search_product"),
    path('password-reset/',auth_views.PasswordResetView.as_view(
        template_name='web/password_reset.html',
        email_template_name='web/reset_password_email.html'),
        name='password_reset'),
    # path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(
    #     template_name='web/password_reset_done.html'),
    #     name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(
        template_name='web/password_reset_confirm.html'),
        name='password_reset_confirm'),
    # path('reset/done/',auth_views.PasswordResetCompleteView.as_view(
    #     template_name='web/password_reset_complete.html'),
    #     name='password_reset_complete'),
    path('product_in_cat/(?P<pk>\d+)/',views.product_in_category, name="product_in_category"),
]

Farmveda/web/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.core.validators import RegexValidator
from django.core.validators import MinLengthValidator

class User(AbstractUser):
    is_seller = models.BooleanField(default=False)
    is_buyer = models.BooleanField(default=False)
    phone = models.CharField(max_length=10, validators=[MinLengthValidator(10),RegexValidator(r'^\d{1,10}$')], default='')
    firm_name = models.CharField(max_length=100,default='')
    website = models.URLField(max_length=100,default='')

class Seller(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE , primary_key = True)
    #rating = 

class Category(models.Model):
    name = models.CharField(max_length = 50)
    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length = 50)
    # category = models.CharField(max_length = 25)
    category = models.ForeignKey(Category, on_delete = models.CASCADE, related_name='products', null= True)
    price = models.CharField(max_length = 45, null = True)
    image = models.FileField(blank = True, null = True)
    seller = models.ForeignKey(User, on_delete = models.CASCADE, related_name='products', null = True)
    #flag to differentiate crawled data from signed up data
    crawled = models.BooleanField(default=False)    
    rating = models.FloatField(default=0)
    quantity = models.CharField(max_length = 50)
    link = models.CharField(max_length = 80, null = True )

    def __str__(self):
        return self.name


class Buyer(models.Model):
    user = models.OneToOneField(User, on_delete= models.CASCADE, primary_key = True)
    wishlist = models.ManyToManyField(Product)


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, null=True)
    item = models.ForeignKey(Product, on_delete = models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return str(self.user.username)

Farmveda/web/templates/web/buyer_loggedin.html
{% extends 'base.html' %}
{% load static %}

{% block css %}

    button:hover{
        transform: scale(1.1);
        box-shadow: 5px 5px 5px black;
    }

    #crd:hover{
        opacity: 0.7;
        background-color: grey;
        transform: scale(1.04);
    }

    #crd:hover .middle{
        opacity:1;
    }

    .middle{
        opacity:0;
        position: absolute;
        left:0;
        right:0;
        top:40%;
    }

    .text{
        font-size:40px;
        color: white;
    }

    .card-text{
        color:black;
    }

    .card-title{
        color:black;
    }

{% endblock %}

{% block body %}

<ul class="nav navbar-nav ml-auto">

        <li class="nav-item mr-3 pt-1">
                <form action="http://localhost:8000/web/search/" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-light btn-lg">
                    <span class="fas fa-search"></span>Search
                </button>
                </form>
        </li>

        <li class="nav-item mr-3 pt-1">
            <form action="{% url 'web:my_profile' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-light btn-lg">
                    <span class="fas fa-user"></span> Profile
            </button>
            </form>
        </li>

        <li class="nav-item mr-3 pt-1">
            <form action="{% url 'web:wishlist' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-light btn-lg">
                <span class="fas fa-heart"></span>&nbspWishlist
            </button>
            </form>
        </li>

        <li class="nav-item mr-3 pt-1">
            <form action="{% url 'web:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-light btn-lg">
                <span class="fas fa-sign-out-alt"></span> Logout
            </button>
            </form>
        </li>
    
</ul>

{% endblock %}

{% block div %}
<br><br><br><br>
<div style="margin-left:10% ; margin-right:10%">
        <div class="card-columns">
        {% for product in products %}
        <a href="{% url 'web:search_product' pk=product.pk %}">
        <div class="card border-dark" id="crd">
            {% if product.image %}
            <img class="card-img-top " src="{{product.image.url}}" alt="Card image cap" height="200" >
            {% else %}
            <img class="card-img-top " src="{% static 'web/images/crop.jpg' %}" alt="Card image cap" height="200" >
            {% endif %}

            <div class="card-body">
                <h5 class="card-title">{{product.name}}</h5>
                <p class="card-text">
                    Seller: {{product.seller}}
                    <br>
                    Price: {{product.price}}
                </p>
        
            </div>

            <div class='middle'>
                    <h1 align='center' class='text'>Click to Open</h1>
            </div>

          </div>
          </a>
          {% endfor %}
          </div>
          </div> 


{% endblock %}

Farmveda/web/templates/web/changepassword.html
{% extends 'base.html' %}

{% block css %}

    button:hover{
        transform: scale(1.1);
        box-shadow: 5px 5px 5px black;
    }

{% endblock %}

{% block body %}

<ul class="nav navbar-nav ml-auto">
        <li class="nav-item mr-3 pt-1">
            <form action="{% url 'web:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-light btn-lg">
                <span class="fas fa-sign-out-alt"></span> Logout
            </button>
            </form>
        </li>
</ul>
{% endblock %}

{% block div %}
<br>
<br><br><br><br>

<div class="container jumbotron bg-light" style="width:500px">
<h1 class="bg-info p-1" align="center">Change Password</h1> <br>

    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <div align="center">
                <button type="submit" class="btn btn-info">Submit</button>
        </div>
    </form>
</div>


{% endblock %}

Farmveda/web/templates/web/edit_details.html
{% extends 'base.html' %}

{% block css %}

    button:hover{
        transform: scale(1.1);
        box-shadow: 5px 5px 5px black;
    }

{% endblock %}

{% block body %}

<ul class="nav navbar-nav ml-auto">
        <li class="nav-item mr-3 pt-1">
            <form action="{% url 'web:my_profile' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-light btn-lg">
                    <span class="fas fa-user"></span> Profile
            </button>
            </form>
        </li>

        <li class="nav-item mr-3 pt-1">
                <form action="{% url 'web:wishlist' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-light btn-lg">
                    <span class="fas fa-heart"></span>&nbspWishlist
                </button>
                </form>
            </li>

        <li class="nav-item mr-3 pt-1">
            <form action="{% url 'web:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-light btn-lg">
                <span class="fas fa-sign-out-alt"></span> Logout
            </button>
            </form>
        </li>
</ul>

{% endblock %}

{% block div %}
<br>
<br><br><br><br>

<div class="container jumbotron bg-light" style="width:500px">
<h1 class="bg-info p-1" align="center">Edit Details</h1> <br>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <div align="center">
        <button type="submit" class="btn btn-info">Submit</button>
        </div>
    </form>
</div>


{% endblock %}

Farmveda/web/templates/web/editprofile.html
{% extends 'base.html' %}

{% block css %}

    button:hover{
        transform: scale(1.1);
        box-shadow: 5px 5px 5px black;
    }

{% endblock %}

{% block body %}

<ul class="nav navbar-nav ml-auto">
        <li class="nav-item mr-3 pt-1">
            <form action="{% url 'web:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-light btn-lg">
                <span class="fas fa-sign-out-alt"></span> Logout
            </button>
            </form>
        </li>
</ul>
{% endblock %}

{% block div %}
<br>
<br><br><br><br>

<div class="container jumbotron bg-light" style="width:500px">
<h1 class="bg-info p-1" align="center">Edit Profile</h1> <br>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <div align="center">
        <button type="submit" class="btn btn-info">Submit</button>
        </div>
    </form>
</div>


{% endblock %}

Farmveda/web/templates/web/myprofile.html
{% extends 'base.html' %}

{% block css %}

    button:hover{
        transform: scale(1.1);
        box-shadow: 5px 5px 5px black;
    }

{% endblock %}

{% block body %}

<ul class="nav navbar-nav ml-auto">
        <li class="nav-item mr-3 pt-1">
            <form action="{% url 'web:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-light btn-lg">
                <span class="fas fa-sign-out-alt"></span> Logout
            </button>
            </form>
        </li>
</ul>
{% endblock %}

{% block div %}
<br>
<br><br><br><br><br><br><br>

<div class = "jumbotron container bg-light" style="width:500px">

<h1 class="bg-info p-1" align="center">Your Profile</h1>

<br>

{% if user.is_buyer is True %}

<ul>
    <li>Username: {{user}}</li>
    <li>First Name: {{user.first_name}}</li>
    <li>Last Name: {{user.last_name}}</li>
    <li>Email: {{user.email}}</li>
    <li>Phone: {{user.phone}}</li>
    <br>
    <div align="center">
    <form action="{% url 'web:edit_profile' %}">
    <button type="submit" class="btn btn-info">
        Edit Profile
    </button>
    </form> 
    <br>
    <form action="{% url 'web:change_password' %}">
    <button tyoe="submit" class="btn btn-info">
        Change Password
    </button>
    </form>
</ul>

{% endif %}

{% if user.is_seller is True %}

<ul>
    <li>Username: {{user}}</li>
    <li>Firm Name: {{user.firm_name}}</li>
    <li>Website: {{user.website}}</li>
    <li>Email: {{user.email}}</li>
    <li>Phone: {{user.phone}}</li>   
    <br>
    <div align="center">
    <form action="{% url 'web:edit_profile' %}">
    <button type="submit" class="btn btn-info">
        Edit Profile
    </button>
    </form> 
    <br>
    <form action="{% url 'web:change_password' %}">
    <button tyoe="submit" class="btn btn-info">
        Change Password
    </button>
    </form>
</ul>

{% endif %}

</div>

{% endblock %}

Farmveda/web/templates/web/options.html
{% extends 'base.html' %}

{% block css %}

    button:hover{
        transform: scale(1.1);
    }

{% endblock %}

{% block body %}
<ul class="nav navbar-nav ml-auto">

        <li class="nav-item mr-3 pt-1">
                <form action="http://localhost:8000/web/search/" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-light btn-lg">
                    <span class="fas fa-search"></span>Search
                </button>
                </form>
        </li>

        
        <li class="nav-item mr-3 pt-1">
            <form action="{% url 'web:login' %}">
            {% csrf_token %}    
            <button type="submit" class="btn btn-light btn-lg">
                <span class="fas fa-sign-in-alt"></span> Login
            </button>
            </form>
        </li>
</ul>
{% endblock %}


{% block div %}

<br> <br> <br> <br> <br> <br>

<div class="jumbotron container bg-light" style="width:500px">
    <div align='center'>
    <h1 class = 'bg-info p-1'> Sign Up as</h1> <br>
    
    <form action="{% url 'web:buyer_signup' %}">
    <button type="submit" class="btn btn-info text-body btn-lg" id="btn1">
      Buyer
    </button>
    </form>
  
    <strong>OR</strong>

    <form action="{% url 'web:seller_signup' %}">
    <button type="submit" class="btn btn-info text-body btn-lg" id="btn2">
      Seller
    </button>
    </form>
    </div>
</div>

{% endblock %}

Farmveda/web/templates/web/password_reset.html
{% extends 'base.html' %}

{% block css %}

    button:hover{
        transform: scale(1.1);
        box-shadow: 5px 5px 5px black;
    }

{% endblock %}

{% block body %}

<ul class="nav navbar-nav ml-auto">
<li class="nav-item pt-1">
        <form action="{% url 'web:signup_options' %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-light btn-lg" id="btn1">
            <span class="fas fa-handshake"></span> SignUp
        </button>
        </form>
    </li>
</ul>

{% endblock %}

{% block div %}

<br> <br> <br> <br> <br> <br>

<div class = " jumbotron container bg-light" style="width:500px">
<h1 class="bg-info p-1" align="center">Reset Password</h1>
<br> <br>
<form method="post" action="{% url 'web:password_reset' %}" >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-info text-body btn-lg">
            <span class="fas fa-sign-in-alt"></span> Request Password Reset
    </button>
</form>
</div>

{% endblock %}

Farmveda/web/templates/web/password_reset_complete.html
<div>
    Your password has been set
</div>

<a href="{% url 'web:login' %}">Log In</a>

Farmveda/web/templates/web/password_reset_done.html
<div>
    An email has been sent
</div>

Farmveda/web/templates/web/product_create.html
{% extends 'base.html' %}
{% block css %}


    #as{
        max-width: 450px;
        background: #FAFAFA;
        padding: 30px;
        margin: 50px auto;
        box-shadow: 1px 1px 25px rgba(0, 0, 0, 0.35);
        border-radius: 10px;
        border: 6px solid #305A72;
    }

    button:hover{
        transform: scale(1.1);
        box-shadow: 5px 5px 5px black;
    }

{% endblock %}

{% block body %}

<ul class="nav navbar-nav ml-auto">



        <li class="nav-item mr-3 pt-1">
            <form action="{% url 'web:my_profile' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-light btn-lg">
                    <span class="fas fa-user"></span> Profile
            </button>
            </form>
        </li>

        <li class="nav-item mr-3 pt-1">
            <form action="{% url 'web:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-light btn-lg">
                <span class="fas fa-sign-out-alt"></span> Logout
            </button>
            </form>
        </li>
    
</ul>

{% endblock %}

{% block div %}

<br><br><br><br>
<div id="as" class="dipov" align="center">
    <h2 class="bg-info p-1">
        Add Details of Your PRODUCT
    </h2> <br> <br>
<form action='.' method='POST' enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-info text-body btn-lg">
        <span class="fas fa-save"></span> Save
    </button>
</div>
</form>




{% endblock %}

Farmveda/web/templates/web/productdetails.html
{% extends 'base.html' %}

{% block css %}

    button:hover{
        transform: scale(1.1);
        box-shadow: 5px 5px 5px black;
    }

{% endblock %}

{% block body %}

<ul class="nav navbar-nav ml-auto">
        {% if not user.is_seller is True %}
        <li class="nav-item mr-3 pt-1">
                <form action="http://localhost:8000/web/search/" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-light btn-lg">
                    <span class="fas fa-search"></span>Search
                </button>
                </form>
        </li>
        {% endif %}

        <li class="nav-item mr-3 pt-1">
            <form action="{% url 'web:my_profile' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-light btn-lg">
                    <span class="fas fa-user"></span> Profile
            </button>
            </form>
        </li>

        {% if not user.is_seller is True %}
        <li class="nav-item mr-3 pt-1">
            <form action="{% url 'web:wishlist' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-light btn-lg">
                <span class="fas fa-heart"></span>&nbspWishlist
            </button>
            </form>
        </li>
        {% endif %}

        <li class="nav-item mr-3 pt-1">
            <form action="{% url 'web:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-light btn-lg">
                <span class="fas fa-sign-out-alt"></span> Logout
            </button>
            </form>
        </li>

</ul>

{% endblock %}

{% block div %}

<br><br><br><br><br><br>
<div class="jumbotron container bg-light" align="center" style="width:500px">
    <h1 class="bg-info p-1" align="center">{{product.name}}</h1>
    <br>
    {% if product.image %}
        <img src="{{product.image.url}}"  height="200" width="200">
        <br><br>
    {% endif %}
    <h4>Price: {{product.price}}</h4>
    {% if product.crawled is True %}
    <h4>Category: {{product.category}}</h4>
    <h4>Website:</h4><a href="{{product.link}}">{{product.link}}</a><br>
    {% else %}
    <h4>Quantity: {{product.quantity}}</h4>
    <h4>Category: {{product.category}}</h4>
    <h4>Contact: {{product.seller.phone}}</h4>
    <h4>Seller E-mail: {{product.seller.email}}</h4>
    {% endif %}
     <br>

    {% if not user.is_buyer is True %}
    <form action = "{% url 'web:edit_details' pk=product.pk %}" method = 'POST'>
        {% csrf_token %}
        <button class="btn btn-info text-body btn-lg">
            <span class="fas fa-plus"></span> Edit Details
        </button>
    </form>
    <br>
    <form action = "{% url 'web:delete_product' pk=product.pk %}" method = 'POST'>
        {% csrf_token %}
        <button class="btn btn-info text-body btn-lg">
            <span class="fas fa-trash-alt"></span> Delete
        </button>
    </form>
    <br>
    {% endif %}

    {% if not user.is_seller is True %}
    <form action = "{% url 'web:add-wishlist' pk=product.pk %}" method = 'POST'>
        {% csrf_token %}
        <button class="btn btn-info text-body btn-lg">
            <span class="fas fa-plus"></span> Add to Wishlist
        </button>
    </form>
    <br>
    {% endif %} 
    <div>
            <h2 align='left'>Reviews:</h2>
            {% for comment in product.comment_set.all %}
            <ul>
                <li> <h5 align='left'>{{ comment.content }}</h5> - <b><i> {{ comment.user }} </i></b> on {{comment.timestamp}}</li>
            </ul>
            {% endfor %}
            {% if not user.is_seller is True %}

            <div style="border: 2px solid grey; border-radius: 5px;background-color: azure; width:400px ; height:200px" align="center" >
            <h2 class="bg-info p-1">Give your Feedback</h2> <br>
            <form action='.' method='POST'>
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-info text-body btn-lg">
                    <span class="fas fa-plus"></span> Add
                </button>
            </form>
            {% endif %}
        </div>
</div>

{% endblock %}

Farmveda/web/templates/web/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}
	
{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'web:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}
	
{% endautoescape %}

Farmveda/web/templates/web/seller_loggedin.html
{% extends 'base.html' %}
{% load static %}

{% block css %}

    button:hover{
        transform: scale(1.1);
        box-shadow: 5px 5px 5px black;
    }

    #crd:hover{
        opacity: 0.7;
        background-color: grey;
        transform: scale(1.04);
    }

    #crd:hover .middle{
        opacity:1;
    }

    .middle{
        opacity:0;
        position: absolute;
        left:0;
        right:0;
        top:40%;
    }

    .text{
        font-size:40px;
        color: white;
    }

    .card-text{
        color:black;
    }

    .card-title{
        color:black;
    }

{% endblock %}

{% block body %}

<ul class="nav navbar-nav ml-auto">


        <li class="nav-item mr-3 pt-1">
            <form action="{% url 'web:my_profile' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-light btn-lg">
                    <span class="fas fa-user"></span> Profile
            </button>
            </form>
        </li>

        <li class="nav-item mr-3 pt-1">
            <form action="{% url 'web:product_create_view' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-light btn-lg">
                <span class="fas fa-plus"></span> Add Products
            </button>
            </form>
        </li>

        <li class="nav-item mr-3 pt-1">
            <form action="{% url 'web:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-light btn-lg">
                <span class="fas fa-sign-out-alt"></span> Logout
            </button>
            </form>
        </li>
    
</ul>

{% endblock %}

{% block div %}

<br><br><br><br> <br>
<!-- <div class = " jumbotron container bg-light" style="width:500px" align='center'>
<h1 class="bg-info p-1">Your Products</h1> <br>
    {% for product in user.products.all %}
    <form action="{% url 'web:product' pk=product.pk %}">
    {% csrf_token %}
        <button type="submit" class="btn btn-success text-body btn-lg">{{product.name}}</button>
    </form>
    <br>    
    {% endfor %}
</div> -->

<div style="margin-left:10% ; margin-right:10%">
        <h1 class="bg-info p-1" align='center'>Your Products</h1> <br>
        <!-- <div class="container" align="center"> -->
        <div class="card-columns">
                {% for product in user.products.all %}
                <a href="{% url 'web:search_product' pk=product.pk %}">
        <div class="card border-dark" id="crd">
            {% if product.image %}
            <img class="card-img-top " src="{{product.image.url}}" alt="Card image cap" height="200" >
            {% else %}
            <img class="card-img-top " src="{% static 'web/images/download.jpeg' %}" alt="Card image cap" height="200" >
            {% endif %}

            <div class="card-body">
                <h5 class="card-title">{{product.name}}</h5>
                <p class="card-text">
                    Seller: {{product.seller}} <br>
                    Price: {{product.price}}
                </p>
                <!-- <form action="{% url 'web:search_product' pk=product.pk %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-success text-body stretched-link">View Details</button>
                </form> -->        
            </div>

            <div class='middle'>
                    <h1 align='center' class='text'>Click to Open</h1>
            </div>

          </div>
          {% endfor %}
          </div>
          </div> 

{% endblock %}

Farmveda/web/templates/web/wishlist.html
{% extends 'base.html' %}

{% block css %}

    button:hover{
        transform: scale(1.1);
        box-shadow: 5px 5px 5px black;
    }

{% endblock %}

{% block body %}

<ul class="nav navbar-nav ml-auto">
 
        <li class="nav-item mr-3 pt-1">
                <form action="http://localhost:8000/web/search/" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-light btn-lg">
                    <span class="fas fa-search"></span>Search
                </button>
                </form>
        </li>
 
    <li class="nav-item mr-3 pt-1">
            <form action="{% url 'web:my_profile' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-light btn-lg">
                    <span class="fas fa-user"></span> Profile
            </button>
            </form>
        </li>

        <li class="nav-item mr-3 pt-1">
            <form action="{% url 'web:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-light btn-lg">
                <span class="fas fa-sign-out-alt"></span> Logout
            </button>
            </form>
        </li>
</ul>

{% endblock %}

{% block div %}

<br><br><br><br> <br>
<div class = " jumbotron container bg-light" align="center" style="width:500px">
<h2 class="bg-info p-1">Your Wishlist</h2> <br>
<ul>
    {% for product in buyer.wishlist.all %}
    {% if product.image %}
    <div style="border: 2px solid grey; border-radius: 5px;background-color: azure; height:400px" align="center">
    {% endif %}
    {% if not product.image %}
    <div style="border: 2px solid grey; border-radius: 5px;background-color: azure; height:150px" align="center">
    {% endif %}  
        <h4>{{product.name}}</h4>
        {% if product.image %}
        <div style="border: 2px solid grey; border-radius: 5px;background-color : white; height:250px" align="center">
        <img src="{{product.image.url}}"  height="200" width="200">
        </div>
        {% endif %}
        <h6>Product category: {{product.category}}</h6>
        <h6>Product price: {{product.price}}</h6>
        <form action = "{% url 'web:remove-wishlist' pk=product.pk %}" method = 'POST'>
            {% csrf_token %}
            <button type="submit" class="btn btn-info btn-lg">
                <span class="fas fa-minus"></span> Remove from wishlist
            </button>
        </form>
    </div>
    <br>
    {% endfor %}
</ul>

{% endblock %}