Farmveda/Farmveda/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('web/', include('web.urls')),
    path('', include('django.contrib.auth.urls'))

]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Farmveda/web/urls.py
from django.urls import path
from django.conf.urls import include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'web'

urlpatterns = [
    path('buyersignup/', views.buyer_signup_view, name='buyer_signup'), 
    path('sellersignup/', views.seller_signup_view, name='seller_signup'),
    path('login/', views.login_view , name='login'), 
    path('loggedin/', views.login_index , name='login_index'),
    path('logout/', views.logout_view, name='logout'),
    path('home/', views.home, name="home"),
    path('options/', views.signup_options,name="signup_options"),
    path('myprofile/',views.my_profile,name="my_profile"),
    path('myprofile/edit/',views.edit_profile,name="edit_profile"),
    path('myprofile/password/',views.change_password,name="change_password"),
    path('search/',include('haystack.urls')),
    path('create/',views.product_create_view,name='product_create_view'),
    path('product/(?P<pk>\d+)/',views.product,name="product"),
    path('product/edit/(?P<pk>\d+)/',views.edit_details,name="edit_details"),
    path('product/delete/(?P<pk>\d+)/',views.delete_product,name="delete_product"),
    path('wishlist/',views.view_wishlist,name="wishlist"),
    path('add-wishlist/(?P<pk>\d+)/',views.add_to_wishlist,name="add-wishlist"),
    path('remove-wishlist/(?P<pk>\d+)/',views.remove_wishlist,name="remove-wishlist"),
    path('search_product/(?P<pk>\d+)/',views.search_product, name="search_product"),
    path('password-reset/',auth_views.PasswordResetView.as_view(
        template_name='web/password_reset.html',
        email_template_name='web/reset_password_email.html'),
        name='password_reset'),
    # path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(
    #     template_name='web/password_reset_done.html'),
    #     name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(
        template_name='web/password_reset_confirm.html'),
        name='password_reset_confirm'),
    # path('reset/done/',auth_views.PasswordResetCompleteView.as_view(
    #     template_name='web/password_reset_complete.html'),
    #     name='password_reset_complete'),
    path('product_in_cat/(?P<pk>\d+)/',views.product_in_category, name="product_in_category"),
]

Farmveda/web/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <style>
        
        body {
            background-image: url("{% static 'web/images/backgroung.jpg' %}");
            background-attachment: fixed;
        }

        #img:hover{
            transform: scale(1.1);
        }
    

        #cat:hover{
            transform: scale(1.0);
            box-shadow: none;
        }

           
        

        {% block css %}
        {% endblock %}

    </style>
    <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
                <!-- Latest compiled and minified CSS -->
                <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

                <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
                <!-- jQuery library -->
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

                <!-- Popper JS -->
                <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

                <!-- Latest compiled JavaScript -->
                <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
                <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    </head>

    <body>
        <nav class="navbar navbar-expand-lg bg-info navbar-light fixed-top">
            <a class="navbar-brand" href = "{% url 'web:home' %}" id='img'>
                <img src="{% static 'web/images/logo.jpg' %}" alt="Code_Busters" style="height:60px; width:200px">
            </a> 
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#contents">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="contents">
            {% if not user.is_seller is True %}
            <form class="form-inline">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <button type="submit" class="btn btn-outline-dark btn-light dropdown-toggle" data-toggle="dropdown" id="cat">
                            Categories                            
                        </button>
                        <div class="dropdown-menu">
                            {% for category in categories %}
                            <a class="dropdown-item" href="{% url 'web:product_in_category' pk=category.pk %}">{{category.name}}</a>
                            {% endfor %}
                        </div>
                    </div>

                    <!-- <input type="text" class="form-control" placeholder="What are you searching for?">
                    
                    <button type="submit" class="btn btn-light ml-sm-2" id="go">
                        <span class="fas fa-search"></span> Go
                    </button> -->
                </div>
            </form>
            {% endif %}
            <p class="google">     &nbsp   &nbsp   &nbsp   &nbsp   &nbsp   &nbsp   <div id="google_translate_element"></div> 
                <script type="text/javascript"> 
                    function googleTranslateElementInit() { 
                      new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element'); 
                    } 
                    </script> 
                      
                    <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script> </p>
            {% block body %}
            {% endblock %}
            </div>
        </nav> 
           
        {% block div %}
        {% endblock %}
        
    </body>
</html>

Farmveda/web/templates/js_inc.html
<script src="{% static 'tellme/feedback.min.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $.feedback({
            ajaxURL: "{% url 'tellme:post_feedback' %}",
            html2canvasURL: "{% static 'tellme/html2canvas.min.js' %}",
            feedbackButton: "#feedback-btn",
            initButtonText: "{% filter escapejs %}{%  include 'tellme/initButtonText.txt' %}{% endfilter %}",
            postHTML: false,
            tpl: {
                description: "{% filter escapejs %}{%  include 'tellme/tpl-description.html' %}{% endfilter %}",
                highlighter: "{% filter escapejs %}{%  include 'tellme/tpl-highlighter.html' %}{% endfilter %}",
                            overview:        "{% filter escapejs %}{%  include 'tellme/tpl-overview.html' %}{% endfilter %}",
                            submitSuccess:"{% filter escapejs %}{%  include 'tellme/tpl-submit-success.html' %}{% endfilter %}",
                            submitError: "{% filter escapejs %}{%  include 'tellme/tpl-submit-error.html' %}{% endfilter %}"
            },
            initialBox: true
        });
    });
</script>